struct compound => 
    symbol: string,
    name : string,
    atomic_no: integer,
    relative_atomic_mass : float,
    valencies: Set Of valency,
    allotropes : Set Of allotrope

struct valency =>  number : integer 

struct allotrope =>
   name : string,
   melting_point : float,
   boiling_point : float,
   density : float