struct compound => 
    molar_mass : float,
    aliases: Set Of alias,
    fromula : Set Of occurring_element

struct alias =>  aliased_name : string 

struct occurring_element =>
   symbol : (*\CDsymboltype*),
   count : integer