SET PAPERSHOME=%~dp0..
SET ERSCRIPTHOME=%PAPERSHOME%\..\..\Distributions\ERScript_r3
SET SAXON_PATH=%ERSCRIPTHOME%\thirdparty\SaxonHE9-7-0-19J
SET JING_PATH=%ERSCRIPTHOME%\thirdparty\jing-20091111\bin
