
struct element => 
    symbol: (*\CDsymboltype*),
    name : (*\CDnametype*),
    atomic_no: (*\CDatomicnumbertype*),
    relative_atomic_mass : (*\CDfloattype*),
    valencies: Set Of valency,
    allotropes : Set Of allotrope

struct valency =>  number : (*\CDvalencynumbertype*)

struct allotrope =>
   name : (*\CDnametype*),
   melting_point : (*\CDfloattype*),
   boiling_point : (*\CDfloattype*),
   density : (*\CDfloattype*)